---
# tasks file for cobra_dev

# We use multiple playbooks because we cannot put tags on role invocations.

- name: Clone git repositories
  git:
    repo: https://github.com/{{ item }}
    dest: ~/go/src/github.com/{{ item }}
  loop: "{{ cobra_repositories }}"


- name: Install golangci-lint
  snap:
    name: golangci-lint
    classic: yes
  become: yes
