---
# vars file for ubuntu_host

personal_settings_file: personal-settings/vars.yml

basic_packages:
  - git
  - jq
  - snapd
  - vim


git_additional_configuration:
  rebase.autosquash: "true"
  core.excludesfile: ~/.gitignore_global

git_config: "{{ git | combine(git_additional_configuration) }}"