---
# tasks file for docker_dev

- name: Clone git repositories
  git:
    repo: https://github.com/{{ item }}
    dest: ~/go/src/github.com/{{ item }}
  loop: "{{ docker_repositories }}"

- name: Add a custom .bashrc to the moby repository
  copy:
    src: moby/.bashrc
    dest: ~/go/src/github.com/moby/moby
