---
# tasks file for docker_dev

- name: Clone git repositories
  git:
    repo: https://github.com/{{ item }}
    dest: ~/go/src/github.com/{{ item }}
  loop: "{{ docker_repositories }}"

- name: Add a custom .bashrc to the moby repository
  copy:
    src: moby/.bashrc
    dest: ~/go/src/github.com/moby/moby

- name: Add aliases for development of bash completion
  blockinfile:
    path: ~/.bash_aliases
    block: |
      alias complete-docker='.  ~/go/src/github.com/docker/cli/contrib/completion/bash/docker'
      alias complete-compose='. ~/go/src/github.com/docker/compose/contrib/completion/bash/docker-compose'
      alias complete-machine='. ~/go/src/github.com/docker/machine/contrib/completion/bash/docker-machine.bash'
